# .github/workflows/update-activity.yml:

name: Update GitHub Activity

on:
  schedule:
    - cron: "*/1 * * * *" # Runs every 1 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update GitHub Activity
        uses: Weixun93/activity-log@v1
        with:
          GITHUB_USERNAME: "Weixun93"
          GITHUB_TOKEN: ${{ secrets.ACTSECRET }} # Ensure this matches the secret name in repository settings
